name: Build action shamiko Zip

on:
  pull_request:
    branches:
      -main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'META-INF'
      - 'LICENSE'
      - 'module.prop'
      - 'post-fs-data.sh'
      - 'service.sh'

# Allow only one concurrent build workflows
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build Flashable Zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: NDK Setup
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndk-version: r28b

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2.0.2

    - name: Build Encore JNI
      run: ndk-build

    - name: Build WebUI
      working-directory: ./webui
      run: |
        bun install
        bun run build
        cp -r ./dist/* ../module/webroot

    - name: Compile Flashable Zip
      id: compileZip
      run: bash .github/scripts/compile_zip.sh

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: mingzun-build
        path: ${{ steps.compileZip.outputs.zipName }}

      run: |
        if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          bash .github/scripts/telegram_bot.sh ${{ steps.compileZip.outputs.zipName }}
        else
          echo "Telegram bot token or chatid is undefined, please add it to repository secrets!"
          exit 1
        fi
