name: Build Module

on:
  workflow_dispatch:    # 允许手动触发
    inputs:
      version:
        description: 'Module version (e.g., 0.7.3)'
        required: true
        default: '0.7.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set build date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create module zip
      run: |
        MODULE_NAME="action_Shamiko"
        ZIP_NAME="${MODULE_NAME}-${{ github.event.inputs.version }}(${{ env.BUILD_DATE }}).zip"
        
        # 创建临时构建目录
        mkdir -p build/${MODULE_NAME}
        
        # 复制所有文件到构建目录（排除.gitignore指定的文件）
        rsync -av --exclude-from='.gitignore' . build/${MODULE_NAME}/
        
        # 进入构建目录并创建zip包
        cd build
        zip -r ${ZIP_NAME} ${MODULE_NAME}
        echo "ZIP_PATH=${ZIP_NAME}" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: action_Shamiko-module
        path: build/${{ env.ZIP_PATH }}