name: Build Shamiko Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Module version (e.g., 0.7.3)'
        required: true
        default: '0.7.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set build date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Create flat module zip
      run: |
        # 设置文件名
        ZIP_NAME="Shamiko-${{ github.event.inputs.version }}(${{ env.BUILD_DATE }}).zip"
        
        # 创建临时目录
        mkdir -p build
        
        # 直接压缩指定文件到ZIP根目录
        zip -j build/"$ZIP_NAME" \
          META-INF/**/* \
          LICENSE \
          module.prop \
          post-fs-data.sh \
          README.md \
          service.sh
        
        echo "ZIP_PATH=$ZIP_NAME" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shamiko-module
        path: build/${{ env.ZIP_PATH }}